// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8kZ-GPfD-XYKiD95a3InBekBSYHTYK1g',
    appId: '1:1044357188582:web:1150ff10bf0d676b1da427',
    messagingSenderId: '1044357188582',
    projectId: 'medicaare-5d595',
    authDomain: 'medicaare-5d595.firebaseapp.com',
    storageBucket: 'medicaare-5d595.firebasestorage.app',
    measurementId: 'G-4XNFHWHWTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyX3bt-A9XEsVDK4ediFWPzfR51DxFfmw',
    appId: '1:1044357188582:android:ad8e0f8dd1b4a0f11da427',
    messagingSenderId: '1044357188582',
    projectId: 'medicaare-5d595',
    storageBucket: 'medicaare-5d595.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2b70eyraA8F2Ky5Tx54Eb5ej5KGuQuxM',
    appId: '1:1044357188582:ios:a234ee960433b9d81da427',
    messagingSenderId: '1044357188582',
    projectId: 'medicaare-5d595',
    storageBucket: 'medicaare-5d595.firebasestorage.app',
    iosBundleId: 'com.example.medicaare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2b70eyraA8F2Ky5Tx54Eb5ej5KGuQuxM',
    appId: '1:1044357188582:ios:a234ee960433b9d81da427',
    messagingSenderId: '1044357188582',
    projectId: 'medicaare-5d595',
    storageBucket: 'medicaare-5d595.firebasestorage.app',
    iosBundleId: 'com.example.medicaare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8kZ-GPfD-XYKiD95a3InBekBSYHTYK1g',
    appId: '1:1044357188582:web:bdd5ecf0b2d2b31b1da427',
    messagingSenderId: '1044357188582',
    projectId: 'medicaare-5d595',
    authDomain: 'medicaare-5d595.firebaseapp.com',
    storageBucket: 'medicaare-5d595.firebasestorage.app',
    measurementId: 'G-Q0E5G38SL1',
  );
}
